### PR TITLE
Updating UI to Windows 11 Style

### PR DESCRIPTION
**Pull request by wherewhere**
After over a month developing. I have update the base controls to the win11 style. If author is still willing to continue developing this project, please accept my request. Hope this project can keep going forever.
image
image
### Updated controls:
- Calendar
- CheckBox
- ComboBox
- ContextMenu
- DatePicker
- Expander
- Hyperlink
- ListBox
- ListView
- Menu
- MenuItem
- PasswordBox
- Pivot
- ProgressBar
- RadioButton
- RepeatButton
- ScrollBar
- Slider
- TabControl
- ToggleButton
- ToolBar
- TreeView
### Unfinnished:
- All controls in ModernWpf.Controls
- In app Acrylic (From FluentWPF)
- Window Backdrop (Mica in Win11 and Acrylic in Win10, I want to make an AppWindow)

### CODE REVIEW

**Comment by MostlyWhat** [comment]
Looks really sick!

**Comment by wherewhere** [comment]
> Looks really sick!

Or do by yourself.

**Comment by ghost1372** [comment]
This project is no longer active, Please continue in a new repo and package

**Comment by chucker** [comment]
> This project is no longer active

Has @Kinnara ever actually confirmed? They made another commit a few months ago.

**Comment by ghost1372** [comment]
> > This project is no longer active
> 
> Has @Kinnara ever actually confirmed? They made another commit a few months ago.

Yes after more than a year he pushed some commits that is not important!

**Comment by Valkirie** [comment]
Good job !

**Comment by artsemionov** [comment]
We need this!

**Comment by dragonfavors** [comment]
good!

**Comment by nlogozzo** [comment]
@wherewhere Can you create a custom nuget package with these updated styles for us to use?

**Comment by wherewhere** [comment]
> @wherewhere Can you create a custom nuget package with these updated styles for us to use?

It have not complete yet. You can fork one and add to your project. So that when you find bugs, you can fix it by your self.

**Comment by Valkirie** [comment]
> > @wherewhere Can you create a custom nuget package with these updated styles for us to use?
> 
> It have not complete yet. You can fork one and add to your project. So that when you find bugs, you can fix it by your self.

Any chance you could investigate why touch inputs are not captured anymore when using ModernWpf ?

**Comment by wherewhere** [comment]
> Any chance you could investigate why touch inputs are not captured anymore when using ModernWpf ? I have remotely no idea where and what to search.

I don't have touchable device. Does it functional in old ModernWpf?

**Comment by Valkirie** [comment]
> > Any chance you could investigate why touch inputs are not captured anymore when using ModernWpf ? I have remotely no idea where and what to search.
> 
> I don't have touchable device. Does it functional in old ModernWpf?

No. It was broken already.

**Comment by Valkirie** [comment]
> > No. It was broken already. There has to be something turning Handled = true somewhere, therefore locking touch inputs.
> 
> Maybe you can debug by block functions one by one. It might course by the custom Window. Is that functional in pure WPF?

Yes it works fine with pure WPF. Still looking into it but no luck so far.

**Comment by BobbyESP** [comment]
@Kinnara Pls, we need to update to this

**Comment by fitojb** [comment]
Everyone: please avoid pestering the maintainers of open-source projects. Remember they mostly work on their projects on their free time.

**Comment by BobbyESP** [comment]
> Everyone: please avoid pestering the maintainers of open-source projects. Remember they mostly work on their projects on their free time.

True, sorry!

**Comment by Valkirie** [comment]
What an amazing job you're doing!

**Comment by Kinnara** [comment]
Thanks for the amazing work. My only suggestion is that if we can revert the attribute order changes and formatting changes, this PR will be easier to review.

**Comment by wherewhere** [comment]
> Thanks for the amazing work. My only suggestion is that if we can revert the attribute order changes and formatting changes, it will be easier to review this PR.

So what need I do?

**Comment by Nuklon** [comment]
> > Thanks for the amazing work. My only suggestion is that if we can revert the attribute order changes and formatting changes, it will be easier to review this PR.
> 
> So what should I do?

I assume he's talking about the added whitespace here and there, such as https://github.com/Kinnara/ModernWpf/blob/c4ebc68f2399497f01e8b52013cd0ece02bd4e51/ModernWpf.Controls/AutoSuggestBox/AutoSuggestBox.xaml#L1, but that's actually an improvement as some whitespace was missing. I'd be easier to review without whitespace changes:
https://github.com/Kinnara/ModernWpf/pull/446/files?diff=split&w=1

**Comment by wherewhere** [comment]
> Not sure if related to Win11 style but I have that page "Suspender" on my app where I'm generating borders/grids on the go for each elements based on running processes. Those elements are not changing background color on theme switch. Any idea ?
> 
> image
> 

You need use DynamicResource.

**Comment by Valkirie** [comment]
`processBorder = new Border()
{
    Padding = new Thickness(20, 12, 12, 12),
    Background = (Brush)Application.Current.Resources["SystemControlBackgroundChromeMediumLowBrush"],
    Tag = Name
};`
This is what I'm already doing.

**Comment by wherewhere** [comment]
> `processBorder = new Border()
> {
>     Padding = new Thickness(20, 12, 12, 12),
>     Background = (Brush)Application.Current.Resources["SystemControlBackgroundChromeMediumLowBrush"],
>     Tag = Name
> };`
> This is what I'm already doing.

In this way the background will only set once. The color will never change. Whatever in Modern WPF or UWP. You need reset the background everytime when you change theme.

**Comment by Valkirie** [comment]
Thanks. Actually I approached the issue differently and it worked.
https://github.com/Valkirie/ControllerService/commit/fb553f7133537e18217aa84cefa8b05a34cfbb13

**Comment by Valkirie** [comment]
Interesting to see you're working on scrolling : https://github.com/Kinnara/ModernWpf/pull/446/commits/db98d92ed941c42a9e7fdf6bffdb4885966b4012

I still can't get my application to register touch inputs :'(

**Comment by wherewhere** [comment]
> Thanks. Actually I approached the issue differently and it worked.
> `SetResourceReference(Control.BackgroundProperty, "SystemControlBackgroundChromeMediumLowBrush");`
> https://github.com/Valkirie/ControllerService/commit/fb553f7133537e18217aa84cefa8b05a34cfbb13

You forget remove Window_ActualThemeChanged​. LOL.

**Comment by wherewhere** [comment]
> Interesting to see you're working on scrolling: https://github.com/Kinnara/ModernWpf/pull/446/commits/db98d92ed941c42a9e7fdf6bffdb4885966b4012
> 
> I still can't get my application to register touch inputs and had to come up with a few tricks to mimick some form of scrolling: https://github.com/Valkirie/ControllerService/blob/ec045baaa0539de42a2791ec61aa3a6981d9441b/HandheldCompanion/Views/Windows/MainWindow.xaml.cs#L664

Funny, scrollviewer support touch by default.

**Comment by YujunA** [comment]
Good job! All you've done really helped me a lot! I do hope this project can go on.

**Comment by YujunA** [comment]
> `processBorder = new Border()
> {
>     Padding = new Thickness(20, 12, 12, 12),
>     Background = (Brush)Application.Current.Resources["SystemControlBackgroundChromeMediumLowBrush"],
>     Tag = Name
> };`
> This is what I'm already doing.

SetResourceReference is a good way you'd better consider.

**Comment by wherewhere** [comment]
Everyone say good job, but no one make contribute...

**Comment by YujunA** [comment]
> Everyone say good job, but no one make contribute... 

That's true. People usually have their own work to do.

**Comment by AYue2021** [comment]
We also like it,how i get it ???
Now the UI I Think it  not good and i want WinUI Style

**Comment by YujunA** [comment]
> We also like it,how i get it ???
> Now the UI I Think it  not good and i want WinUI Style 

That's right. Winning style is my favorite. I can't agree more!

**Comment by AYue2021** [comment]
> 我正在尝试安装 .net4.5 SDK。我的可触摸设备找不到.net4.5.2 SDK，新安装的vs2022很丑陋...

You can use RDP Client on iPhone or Android Device,
it's will give you a touch screnn

**Comment by AYue2021** [comment]
> > 我们也喜欢它，我如何得到它???现在的UI我认为它不好，我想要WinUI风格
> 
> 没错。WinUI风格是我的最爱。我完全同意！

Then,My application wants support on Windows7
if you want WinUI,You can try WindowsXamlHost

**Comment by YujunA** [comment]
> > > 我们也喜欢它，我如何得到它???现在的UI我认为它不好，我想要WinUI风格
> > 
> > 没错。WinUI风格是我的最爱。我完全同意！
> 
> Then,My application wants support on Windows7
> if you want WinUI,You can try WindowsXamlHost

Xaml host requires Windows 10 or later.
Many of my clients are still using Windows 7 or 8.1, otherwise I would simply give up WPF and take up Winning 3 instead. (my poor programming level and English speaking level)

**Comment by AYue2021** [comment]
> > > > 我们也喜欢它，我如何得到它???现在的UI我认为它不好，我想要WinUI风格
> > > 
> > > 
> > > 没错。WinUI风格是我的最爱。我完全同意！
> > 
> > 
> > 然后，我的应用程序想要Windows7上的支持，如果你想要WinUI，你可以试试WindowsXamlHost
> 
> Xaml 主机需要 Windows 10 或更高版本。我的许多客户仍在使用Windows 7或8.1，否则我会简单地放弃WPF并采用WinUI 3。（我的编程水平和英语口语水平较差）

Are you form China????
wherewhere is Chinese too.

**Comment by YujunA** [comment]
> > > > > 我们也喜欢它，我如何得到它???现在的UI我认为它不好，我想要WinUI风格
> > > > 
> > > > 
> > > > 没错。WinUI风格是我的最爱。我完全同意！
> > > 
> > > 
> > > 然后，我的应用程序想要Windows7上的支持，如果你想要WinUI，你可以试试WindowsXamlHost
> > 
> > Xaml 主机需要 Windows 10 或更高版本。我的许多客户仍在使用Windows 7或8.1，否则我会简单地放弃WPF并采用WinUI 3。（我的编程水平和英语口语水平较差）
> 
> Are you form China????
> "wherewhere" is Chinese man too.

Of course, aren't you too?!

**Comment by AYue2021** [comment]
> 当然，你不是也是吗？！两个英语水平差的中国人用英语说话真是个笑话。

我去编译一下作者的库,看看能用吗

**Comment by YujunA** [comment]
> 
> > 当然，你不是也是吗？！两个英语水平差的中国人用英语说话真是个笑话。
> 
> 我去编译一下作者的库,看看能用吗

我编译了下wherewhere/ModernWpf （他个人fork的版本），整体还可以，不过细节上还有待改进，还有些控件没完成。

**Comment by AYue2021** [comment]
> > > 当然，你不是也是吗？！两个英语水平差的中国人用英语说话真是个笑话。
> > 
> > 
> > 我去编译一下作者的库,看看能用吗
> 
> 我编译了下wherewhere/ModernWpf （他个人fork的版本），整体还可以，不过细节上还有待改进，还有些控件没完成。

为啥我编译时,疯狂报错,最后我改后报错WinRT问题了

**Comment by YujunA** [comment]
> > > > 当然，你不是也是吗？！两个英语水平差的中国人用英语说话真是个笑话。
> > > 
> > > 
> > > 我去编译一下作者的库,看看能用吗
> > 
> > 我编译了下wherewhere/ModernWpf （他个人fork的版本），整体还可以，不过细节上还有待改进，还有些控件没完成。
> 
> 为啥我编译时,疯狂报错,最后我改后报错WinRT问题了

我先是下了个.net framework 4.6.2 的sdk和目标包，结果还是报错。不过这个时候ModernWpf.SampleApp/bin/Debug里其实已经有东西了，运行就好。

**Comment by AYue2021** [comment]
image
ok,把452、net31、net50全删了就好了

**Comment by YujunA** [comment]
> image
> ok,把452、net31、net50全删了就好了

是的，应该是.net版本有问题

**Comment by wherewhere** [comment]
诶？你们回复为什么会自动翻译？

**Comment by YujunA** [comment]
> 诶？你们回复为什么会自动翻译？

没有吧，应该是 @AYue2021 手动翻译的

**Comment by AYue2021** [comment]
> 诶？你们回复为什么会自动翻译？

(我没关浏览器自动翻译

**Comment by AYue2021** [comment]
发现拿出来用并不是很理想(NavigationView)
UI库也没什么好用的,没办法,这东西在Debug,只能用原版+MahApp凑合用了

**Comment by YujunA** [comment]
> 发现拿出来用并不是很理想(NavigationView)
> UI库也没什么好用的,没办法,这东西在Debug,只能用原版+MahApp凑合用了

[wherewhere个人项目](github.com/wherewhere/ModernWpf)里的navigationview我觉得还行，不过项目还在开发阶段，会有些许bug。所以我打算等这个项目开发完全之后再用。

**Comment by YujunA** [comment]
> > 诶？你们回复为什么会自动翻译？
> 
> (我没关浏览器自动翻译

我用的 Github Mobile 。

**Comment by AYue2021** [comment]
image
如你所见,我直接复制了MahApp的RadioButton,
(原版的我觉得不好看)

**Comment by YujunA** [comment]
> image
> 如你所见,我直接复制了MahApp的RadioButton,
> (原版的我觉得不好看)
> 

确实，而且button, checkbox, radiobutton 和一些其他的控件动画和细节还不是很完善。

**Comment by AYue2021** [comment]
> 确实，而且button, checkbox, radiobutton 和一些其他的控件动画和细节还不是很完善。
对于reveal效果,我在https://blog.walterlv.com/post/fluent-design-reveal-brush-in-wpf.html上找到了
对于Checkbox那个动效,要AnimationIcon配合之后所成的
(既然做不出,那直接用Win10的Fluent Design凑合上去

**Comment by YujunA** [comment]
> > 确实，而且button, checkbox, radiobutton 和一些其他的控件动画和细节还不是很完善。
> 
> 
> 对于reveal效果,我在https://blog.walterlv.com/post/fluent-design-reveal-brush-in-wpf.html   上找到了
> 对于Checkbox那个动效,要AnimationIcon配合之后所成的
> (既然做不出,那直接用Win10的Fluent Design凑合上去
> 
> 

这篇文章上的reveal做法非常不建议。我试过，会严重拖慢性能，而且在多线程的时候还容易报错，个人比较推荐[sourcechord/FluentWPF](https://github.com/sourcechord/FluentWPF)，相比之下他做得更成熟，没有什么大问题。

**Comment by AYue2021** [comment]
> > > 确实，而且button, checkbox, radiobutton 和一些其他的控件动画和细节还不是很完善。
> > 
> > 
> > 对于reveal效果,我在https://blog.walterlv.com/post/fluent-design-reveal-brush-in-wpf.html   上找到了
> > 对于Checkbox那个动效,要AnimationIcon配合之后所成的
> > (既然做不出,那直接用Win10的Fluent Design凑合上去
> 
> 这篇文章上的reveal做法非常不建议。我试过，会严重拖慢性能，而且在多线程的时候还容易报错，个人比较推荐[sourcechord/FluentWPF](https://github.com/sourcechord/FluentWPF)，相比之下他做得更成熟，没有什么大问题。

越想越奇葩,当时用的时候Acrylic效果老是不出,用官方的sample能看,但是一移动又没了

**Comment by YujunA** [comment]
> > > > 确实，而且button, checkbox, radiobutton 和一些其他的控件动画和细节还不是很完善。
> > > 
> > > 
> > > 对于reveal效果,我在https://blog.walterlv.com/post/fluent-design-reveal-brush-in-wpf.html   上找到了
> > > 对于Checkbox那个动效,要AnimationIcon配合之后所成的
> > > (既然做不出,那直接用Win10的Fluent Design凑合上去
> > 
> > 这篇文章上的reveal做法非常不建议。我试过，会严重拖慢性能，而且在多线程的时候还容易报错，个人比较推荐[sourcechord/FluentWPF](https://github.com/sourcechord/FluentWPF)，相比之下他做得更成熟，没有什么大问题。
> 
> 越想越奇葩,当时用的时候Acrylic效果老是不出,用官方的sample能看,但是一移动又没了

他的acrylic本质上就是一个visualbrush模拟背景然后加个blureffect，所以性能有差效果也不好。（还要指定target为acrylic下方的背景控件，因此不要在用了acrylic的空间上加transform之类的，要不然acrylic会错位）

**Comment by AYue2021** [comment]
https://user-images.githubusercontent.com/79188080/177072880-0b74028d-1395-4646-bd36-bb0e92e8d9e2.mp4

**Comment by YujunA** [comment]
> https://user-images.githubusercontent.com/79188080/177072880-0b74028d-1395-4646-bd36-bb0e92e8d9e2.mp4
> 
> Github的问题,右键另存为到本地就能看见了



为啥我的是这样？

**Comment by AYue2021** [comment]
> 为啥我的是这样？

啦啦啦其实这是我的App
新版应该没有这个BUG了,毕竟重写了一遍
不过我现在没用这个所谓的"0.10.0"

**Comment by YujunA** [comment]
> > 为啥我的是这样？
> 
> 啦啦啦其实这是我的App
> 新版应该没有这个BUG了,毕竟重写了一遍
> 不过我现在没用这个所谓的"0.10.0"
> 毕竟我需要NavigationView这个控件

应该是版本问题，要不你用新的吧

**Comment by AYue2021** [comment]
> > 啦啦啦其实这是我的App
> > 新版应该没有这个BUG了,毕竟重写了一遍
> > 不过我现在没用这个所谓的"0.10.0"
> > 毕竟我需要NavigationView这个控件
> 
> 应该是版本问题，要不你用新的吧

但是组件切换我认为NavigationView是最好的
(找到这个Nuget包已经很万幸了)

**Comment by YujunA** [comment]
> > > 为啥我的是这样？
> > 
> > 啦啦啦其实这是我的App
> > 新版应该没有这个BUG了,毕竟重写了一遍
> > 不过我现在没用这个所谓的"0.10.0"
> > 毕竟我需要NavigationView这个控件
> 
> 应该是版本问题，要不你用新的吧

0.10.0 的navigationview和winui的几乎一模一样，比旧版好看多了

**Comment by AYue2021** [comment]
> > > > 为啥我的是这样？
> > > 
> > > 
> > > 啦啦啦其实这是我的App
> > > 新版应该没有这个BUG了,毕竟重写了一遍
> > > 不过我现在没用这个所谓的"0.10.0"
> > > 毕竟我需要NavigationView这个控件
> > 
> > 
> > 应该是版本问题，要不你用新的吧
> 
> 0.10.0 的navigationview和winui的几乎一模一样，比旧版好看多了

我编译出来后,无法显示.....

**Comment by YujunA** [comment]
> > > > > 为啥我的是这样？
> > > > 
> > > > 
> > > > 啦啦啦其实这是我的App
> > > > 新版应该没有这个BUG了,毕竟重写了一遍
> > > > 不过我现在没用这个所谓的"0.10.0"
> > > > 毕竟我需要NavigationView这个控件
> > > 
> > > 
> > > 应该是版本问题，要不你用新的吧
> > 
> > 0.10.0 的navigationview和winui的几乎一模一样，比旧版好看多了
> 
> 我编译出来后,无法显示.....

**Comment by YujunA** [comment]
> > > > > 为啥我的是这样？
> > > > 
> > > > 
> > > > 啦啦啦其实这是我的App
> > > > 新版应该没有这个BUG了,毕竟重写了一遍
> > > > 不过我现在没用这个所谓的"0.10.0"
> > > > 毕竟我需要NavigationView这个控件
> > > 
> > > 
> > > 应该是版本问题，要不你用新的吧
> > 
> > 0.10.0 的navigationview和winui的几乎一模一样，比旧版好看多了
> 
> 我编译出来后,无法显示.....

?!
额
我这边踢。挺好的
这就有亿点奇怪。。。
总之我是打算等这个项目全部开发完之后再用呢

**Comment by AYue2021** [comment]
> > > 0.10.0 的navigationview和winui的几乎一模一样，比旧版好看多了
> > 我编译出来后,无法显示.....

image

**Comment by AYue2021** [comment]
image

ok了,顺利解决,不过想要SampleApp那种的话我看看

**Comment by AYue2021** [comment]
image

Done...
<Thickness x:Key="NavigationViewContentMargin">0,48,0,0</Thickness>

**Comment by YujunA** [comment]
> image
> 
> Done...
> <Thickness x:Key="NavigationViewContentMargin">0,48,0,0</Thickness>

祝贺！

**Comment by AYue2021** [comment]
> We need this!

Hi here
image

Yeah I know you want it

**Comment by AYue2021** [comment]
> Tnx，看起来很棒。此项目不再处于活动状态，请在新的存储库和包中继续

Now it's a fork there : https://github.com/wherewhere/ModernWpf

**Comment by AYue2021** [comment]
> 看起来真的很恶心！

Acrylic here!!!!
image

**Comment by YujunA** [comment]
> 
> 
> 
> > 看起来真的很恶心！
> 
> Acrylic here!!!!
> image
> 

咋了？还行吧

**Comment by AYue2021** [comment]
> > > 看起来真的很恶心！
> > 
> > 
> > Acrylic here!!!!
> > image
> 
> 咋了？还行吧

属实把我搞难了-----这图标用Fonticon一个一个套上才能兼容Win7

**Comment by wherewhere** [comment]
请不要带上一堆回复，好丑的。。。

**Comment by AYue2021** [comment]
总觉得ScrollViewer是不是少了点动画

**Comment by wherewhere** [comment]
你们可以到我的fork项目里面讨论，开个discuss。。。

**Comment by YujunA** [comment]
> 你们可以到我的fork项目里面讨论，开个discuss。。。

可以麻烦你开一个吗，我的旧版github手机版开不了（也许是我不会开

**Comment by AYue2021** [comment]
> 可以麻烦你开一个吗，我的旧版github手机版开不了（也许是我不会开

https://github.com/wherewhere/ModernWpf/discussions/9

**Pull request closed without merging**
